import { NextRequest, NextResponse } from 'next/server';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface SalesmanPerformanceEntry {
  name: string;
  transactions: number;
  revenue: number;
  commission: number;
}

interface TopProductEntry {
  name: string;
  quantity: number;
  revenue: number;
}

interface DayEndSummary {
  totalTransactions: number;
  totalRevenue: number;
  paymentBreakdown: {
    cash: number;
    card: number;
    transfer: number;
    other?: number;
  };
  salesmanPerformance?: Record<string, SalesmanPerformanceEntry>;
  topProducts?: TopProductEntry[];
}

async function getCurrentUser(request: NextRequest) {
  try {
    const session = request.cookies.get('session');
    if (!session) return null;
    return JSON.parse(session.value);
  } catch {
    return null;
  }
}

const formatCurrency = (value: number) =>
  new Intl.NumberFormat('en-MY', { style: 'currency', currency: 'MYR' }).format(value || 0);

const formatDateTime = (value: Date) =>
  new Intl.DateTimeFormat('en-MY', {
    dateStyle: 'medium',
    timeStyle: 'short',
    hour12: false,
  }).format(value);

export async function POST(request: NextRequest) {
  try {
    const currentUser = await getCurrentUser(request);
    if (!currentUser) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const { date, branch, summary, cashCount, reconciliationNotes, closedBy, closedAt } = body as {
      date: string;
      branch: string;
      summary: DayEndSummary;
      cashCount?: number;
      reconciliationNotes?: string;
      closedBy?: string;
      closedAt?: string;
    };

    if (!date || !branch || !summary) {
      return NextResponse.json({ error: 'Missing required data' }, { status: 400 });
    }

    const doc = new jsPDF('p', 'mm', 'a4');
    const pageWidth = doc.internal.pageSize.getWidth();
    const generatedAt = new Date();
    const avgTransaction = summary.totalTransactions > 0
      ? summary.totalRevenue / summary.totalTransactions
      : 0;
    const actualCashCount = cashCount || 0;
    const discrepancy = actualCashCount - summary.paymentBreakdown.cash;
    const otherAmount = summary.paymentBreakdown.other || 0;
    const closedByText = closedBy || currentUser.name || currentUser.username || 'Admin';
    const closedAtText = closedAt ? formatDateTime(new Date(closedAt)) : formatDateTime(generatedAt);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.text('DAY END CLOSING REPORT', 14, 16);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text(`Branch: ${branch}`, 14, 24);
    doc.text(`Date: ${date}`, 14, 29);
    doc.text(`Generated At: ${formatDateTime(generatedAt)}`, 14, 34);
    doc.text(`Generated By: ${currentUser.name || currentUser.username || 'Admin'} (${currentUser.role || 'Admin'})`, 14, 39);
    doc.text(`Closed By: ${closedByText}`, 14, 44);
    doc.text(`Closed At: ${closedAtText}`, 14, 49);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('1. Summary Report', 14, 58);

    autoTable(doc, {
      startY: 62,
      theme: 'grid',
      head: [['Metric', 'Value']],
      body: [
        ['Total Transactions', String(summary.totalTransactions)],
        ['Total Revenue', formatCurrency(summary.totalRevenue)],
        ['Average Transaction', formatCurrency(avgTransaction)],
        ['System Cash Total', formatCurrency(summary.paymentBreakdown.cash)],
        ['Actual Cash Count', formatCurrency(actualCashCount)],
        ['Cash Discrepancy', formatCurrency(discrepancy)],
      ],
      headStyles: { fillColor: [30, 64, 175] },
    });

    const tableEndY = (doc as jsPDF & { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY ?? 62;
    doc.setFontSize(12);
    doc.text('2. Details Report Harian', 14, tableEndY + 12);

    autoTable(doc, {
      startY: tableEndY + 16,
      theme: 'striped',
      head: [['Payment Method', 'Amount', 'Percentage']],
      body: [
        ['Cash', formatCurrency(summary.paymentBreakdown.cash), `${summary.totalRevenue > 0 ? ((summary.paymentBreakdown.cash / summary.totalRevenue) * 100).toFixed(1) : '0.0'}%`],
        ['Card', formatCurrency(summary.paymentBreakdown.card), `${summary.totalRevenue > 0 ? ((summary.paymentBreakdown.card / summary.totalRevenue) * 100).toFixed(1) : '0.0'}%`],
        ['Transfer', formatCurrency(summary.paymentBreakdown.transfer), `${summary.totalRevenue > 0 ? ((summary.paymentBreakdown.transfer / summary.totalRevenue) * 100).toFixed(1) : '0.0'}%`],
        ['Other', formatCurrency(otherAmount), `${summary.totalRevenue > 0 ? ((otherAmount / summary.totalRevenue) * 100).toFixed(1) : '0.0'}%`],
      ],
      headStyles: { fillColor: [30, 64, 175] },
    });

    if (summary.topProducts && summary.topProducts.length > 0) {
      const topY = (doc as jsPDF & { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY ?? tableEndY + 16;
      doc.setFontSize(11);
      doc.text('2.1 Top 5 Products', 14, topY + 10);
      autoTable(doc, {
        startY: topY + 13,
        theme: 'grid',
        head: [['Product', 'Quantity', 'Revenue']],
        body: summary.topProducts.slice(0, 5).map((item) => [item.name, String(item.quantity), formatCurrency(item.revenue)]),
        headStyles: { fillColor: [51, 65, 85] },
      });
    }

    const notesY = (doc as jsPDF & { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY ?? 120;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('3. Reconciliation Notes', 14, notesY + 10);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    const notes = reconciliationNotes?.trim() || 'No reconciliation notes provided.';
    doc.text(doc.splitTextToSize(notes, pageWidth - 28), 14, notesY + 16);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('4. Sign-off', 14, 245);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text('Prepared By', 14, 255);
    doc.text('Verified By', 80, 255);
    doc.text('Approved By', 145, 255);
    doc.line(14, 270, 65, 270);
    doc.line(80, 270, 131, 270);
    doc.line(145, 270, 196, 270);
    doc.setFontSize(8);
    doc.text('This report is confidential and for authorized personnel only.', 14, 278);

    const pages = doc.getNumberOfPages();
    for (let page = 1; page <= pages; page++) {
      doc.setPage(page);
      doc.setFontSize(8);
      doc.text(`Page ${page} of ${pages}`, pageWidth - 30, 289);
    }

    const pdfBytes = doc.output('arraybuffer');
    return new NextResponse(pdfBytes, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="DayEndReport_${date}_${branch}.pdf"`,
      },
    });
  } catch (error) {
    console.error('Error in POST /api/day-end/export:', error);
    return NextResponse.json({ error: 'Failed to export report' }, { status: 500 });
  }
}
